### ISSUE TITLE
Cross-platform problem: win10

### ISSUE THREAD

**Issue by valeriy-simakov** [networkservicemesh/sdk-vppagent#216]
During assembly, we have the following errors:
1. pkg\networkservice\mechanisms\directmemif\proxy\proxy.go:255:31: undefined: syscall.Recvmsg
2. pkg\networkservice\mechanisms\directmemif\proxy\proxy.go:269:14: undefined: syscall.Sendmsg
3. pkg\tools\netnsinode\netnsinode.go:53:31: undefined: syscall.Stat_t

**Comment by denis-tingajkin** [comment]
The root cause of this issue that `sdk-vppagent` is not cross-platform. I think it is expected because of vpp supported only next plaforms {`Debian`, `Ubuntu 16.04`, `Centos 7.3`}
@edwarnicke  What do you think?

**Comment by edwarnicke** [comment]
sdk-vppagent is not cross platform to windows.  vpp and vpp-agent currently targets linux, and requires posix.

**Comment by denis-tingajkin** [comment]
@edwarnicke also I think we can notice this point in README file
