### ISSUE TITLE
Suggestion: Add integration tests to verify that result vpp-config is correct

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk-vppagent#39]
## Problem statement

The unit tests can not guarantee that the result vpp-config of chained client/server elements is correct. 
The unit tests can not guarantee that the result vpp-config will be applied correctly on vpp-agent side. 

### Alternative problem

If we imagine that our chained elements correctly builds vpp-config then we can face the next cases:

**Case1:** 
 
1. The developer implements a new feature based on vpp-agent.
2. At first, the developer provides PR to sdk-vppagent
3. PR passed all tests and it has been merged
4. The developer implemented the second part of the feature in the main NSM repo.

**Expected**: PR pass CI  in the main repo. 
**Actual**: Implemented solution at step 2 could be not suitable with vpp-agent. The developer should back to step 2 and provide fixes.

**Case 2:**

1. Repo `sdk-vppagent` updated `vpp-agent` version.
2. All tests passed on the master branch in `sdk-vppagent` repo.
3. Main NSM repo updated dependency on `sdk-vppagent`.

**Expected**: CI should pass after update dep on sdk-vppagent
**Actual**: CI can fail because something can be changed on vpp-agent side and our configs can be not suitable with the new version of vpp-agent.

## Potential solution

Add integration tests. The tests can be similar to integration tests in vpp-agent repo.

**Comment by edwarnicke** [comment]
@denis-tingajkin I'd like to move integration tests further downstream in the repo pipeline and keep just to unit tests in the sdk-* repos.  Keep their CI light and quick, and the overall repos simple.

**Comment by denis-tingajkin** [comment]
@edwarnicke yes, I agree we can try to use `Repo Pipelining` to solve this issue.
